# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: CI Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --pure-lockfile

      - name: Run Jest tests and generate coverage report
        run: yarn test --coverage
        env:
          REMARKABLE_DEVICE_TOKEN: ${{ secrets.REMARKABLE_DEVICE_TOKEN }}
          REMARKABLE_SESSION_TOKEN: ${{ secrets.REMARKABLE_SESSION_TOKEN }}
  lint:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --pure-lockfile

      - name: Run Standard linter
        run: yarn dev:lint
